# Generated by Django 4.2 on 2024-05-10 09:35

from django.db import migrations, models
import django.db.models.deletion
import inscriptionApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=250)),
                ('postnom', models.TextField(max_length=250)),
                ('prenom', models.TextField(max_length=250)),
                ('sexe', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to=inscriptionApp.models.upload_image_etudiant)),
            ],
            options={
                'db_table': 'tbl_etudiant',
            },
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField(max_length=250)),
                ('sigle', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_faculte',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField(max_length=250)),
                ('sigle', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_promotion',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('refEtudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptionApp.etudiant')),
                ('refFaculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptionApp.faculte')),
                ('refPromotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptionApp.promotion')),
            ],
            options={
                'db_table': 'tbl_inscription',
            },
        ),
    ]
